bookstore/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from products import views
from products.views import CheckoutView, CartView

app_name = "core"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", views.home, name="home"),
    path("categories/<int:category_id>/", views.category_books, name="category_books"),
    path("users/", views.users, name="users"),
    path("books/", views.book_list, name="book_list"),
    path("books/<int:id>/", views.book_detail, name="book_detail"),
    path("search/", views.search, name="search"),
    path("checkout/", CheckoutView.as_view(), name="check_out"),
    path("cart/", login_required(CartView.as_view()), name="cart"),
    path("add_to_cart<str:book_title>/", views.add_to_cart, name="add_to_cart"),
    path('profile/', views.profile, name='profile'),
    path("remove_from_cart/<str:book_title>/", views.remove_from_cart, name="remove_from_cart"),
    path("login/", views.login, name='login'),
    path('add_to_wishlist/<int:book_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/<int:book_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('profile/edit-info/', views.edit_user_info, name='settings'),
]

products/models.py
import random

from django.contrib.auth.models import User
from django.db import models


class UserPayment(models.Model):
    PAYMENT_CHOICES = [
        ("CC", "Credit Card"),
        ("DC", "Debit Card"),
        ("PP", "PayPal"),
        ("CB", "Cash on Delivery"),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    payment_type = models.CharField(choices=PAYMENT_CHOICES, max_length=2)
    expiry_date = models.DateField(null=True)

    def __str__(self):
        return f"{self.user.username} - {self.payment_type}"

    # class Meta:
    #     constraints = [
    #         models.UniqueConstraint(
    #             fields=['user_id', 'payment_type'], name='user_payment'
    #         )
    #     ]


class UserAddress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address_line = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    postal_code = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    mobile = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.user.username} - {self.address_line}"

    # class Meta:
    #     constraints = [
    #         models.UniqueConstraint(
    #             fields=['user_id', 'address_line'], name='user_address'
    #         )
    #     ]


class Cart(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField()


class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(default="No description provided")

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=255, unique=True)
    author = models.CharField(max_length=255)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField(default=0)
    summary = models.TextField(default="No description provided")
    img_path = models.CharField(max_length=255, default=None, null=True)

    def save(self, *args, **kwargs):
        if not self.pk:  # if the book is new, then randomize its quantity
            self.quantity = random.randint(10, 30)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.title} - {self.author}"


class CartItems(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    # class Meta:
    #     constraints = [
    #         models.UniqueConstraint(
    #             fields=['cart_id', 'book_id'], name='book_cart'
    #         )
    #     ]


class Order(models.Model):
    STATUS_CHOICES = [
        ("Pending", "Pending"),
        ("Processing", "Processing"),
        ("Shipped", "Shipped"),
        ("Delivered", "Delivered"),
        ("Cancelled", "Cancelled"),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.ForeignKey(UserAddress, on_delete=models.CASCADE)
    status = models.CharField(max_length=40, choices=STATUS_CHOICES)
    shipped_date = models.DateField(null=True)
    order_date = models.DateField()

    def __str__(self):
        return f"{self.user.username} - {self.status}"


class OrderDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.order} - {self.book} - {self.quantity}"
    
class WishList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

products/forms.py
from django import forms
import phonenumbers
from .models import UserPayment, User

"""class BookForms(forms.ModelForm):
    class Meta:
        model = Book
        fields = "__all__"

        labels = {
            'title' : 'Title',
            'author' : 'Author',
            'created_at' : 'Publication Date',
            'updated_at' : 'Republication Date',
            'price' : 'Price',
            'quantity' : 'Quantity',
            'summary' : 'Summary',
        }
        widgets = {
            'title': forms.TextInput(),
            'author': forms.TextInput(),
            'created_at': forms.DateTimeInput(),
            'updated_at': forms.DateTimeInput(),
            'price': forms.ModelForm(),
            'quantity': forms.NumberInput(),
            'summary': forms.Textarea(),
        }
"""

PAYMENT_CHOICES = [
    ("CC", "Credit Card"),
    ("DC", "Debit Card"),
    ("PP", "PayPal"),
    ("CB", "Cash on Delivery"),
]


class CheckoutForm(forms.Form):
    shipping_address = forms.CharField(max_length=255)
    shipping_city = forms.CharField(max_length=255)
    shipping_country = forms.CharField(max_length=255)
    postal_code = forms.CharField(max_length=255)
    mobile = forms.CharField(max_length=255)
    payment_method = forms.ChoiceField(choices=UserPayment.PAYMENT_CHOICES)

    def clean_mobile(self):
        mobile = str(self.cleaned_data.get("mobile"))
        try:
            mobile = phonenumbers.parse(mobile, "VN")
        except phonenumbers.NumberParseException:
            raise forms.ValidationError("Mobile number is invalid")
        if not phonenumbers.is_valid_number(mobile):
            raise forms.ValidationError("Mobile number is not a valid VN number")
        return mobile.national_number


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name"]

templates/base.html
{% load bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>
        {% block title %}
        Bookstore Web App
        {% endblock %}
    </title>
    {% bootstrap_css %}

    <style>
        .navbar-brand img {
            max-height: 40px;
            max-width: 40px;
            border-radius: 50%;
        }
    </style>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="http://127.0.0.1:8000/">
                Bookstore Web App
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="http://127.0.0.1:8000/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="http://127.0.0.1:8000/books/">Books</a>
                    </li>
                </ul>
                <form class="d-flex mx-auto" method="get" action="{% url 'search' %}" style="width: 70%;">
                    <input class="form-control me-2" type="search" name="q" placeholder="Find the book of your dreams..." aria-label="Search" style="width: 80%;">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                <div class="ms-auto">
                    <!-- View Cart button -->
                    <a class="navbar-brand me-3" href="{% url 'cart' %}">
                        <img src={% static 'logo/cart.jpg' %} alt="View your cart">
                    </a>

                    <!-- Profile button -->
                    {% if request.user.is_authenticated %}
                        <a class="navbar-brand" href="{% url 'profile' %}">
                            <img src="{% static 'logo/logo2.jpg' %}" alt="Profile">
                        </a>
                    {% else %}
                        <a class="navbar-brand" href="{% url 'login' %}">
                            <img src="{% static 'logo/logo2.jpg' %}" alt="Profile">
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    <div class="container mt-4">
        {% if messages %}
            <div class="mt-3">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        {% block content %}
        {% endblock %}
    </div>

    {% bootstrap_javascript %}

    <script>
        document.querySelector('form').addEventListener('submit', function(event) {
            event.preventDefault();
            window.location.href = '/search/?q=' + document.querySelector('input[name="q"]').value;
        });
    </script>
</body>
</html>

templates/book_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {{ book.title }}
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <!-- Book Image -->
    <div class="col-md-4">
      <img src="{% static book.img_path %}" alt="{{ book.title }}" class="img-fluid" style="height: 450px; width: 450px">
    </div>
    <!-- Book Details -->
    <div class="col-md-8">
      <div class="book-details">
        <!-- Book Title -->
        <h1><span class="highlight">{{ book.title }}</span></h1>
        <!-- Author, Price, Quantity -->
        <p><strong>Author:</strong> {{ book.author }}</p>
        <p><strong>Price:</strong> {{ book.price }}</p>
        <p><strong>Quantity:</strong> {{ book.quantity }}</p>
        <p><strong>Summary:</strong> {{ book.summary }}</p>

        <!-- Add to Cart Button -->
        <form method="post" action="{% url 'add_to_cart' book.title %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Add to Cart</button>
        </form>

        <!-- Wishlist Button -->
        {% if user.is_authenticated %}
          {% if wishlisted %}
            <form method="post" action="{% url 'remove_from_wishlist' book.id %}" class="mt-3">
              {% csrf_token %}
              <button type="submit" class="btn btn-success">Wishlisted</button>
            </form>
          {% else %}
            <form method="post" action="{% url 'add_to_wishlist' book.id %}" class="mt-3">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary">Add to Wishlist</button>
            </form>
          {% endif %}
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/book_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Book List
{% endblock %}

{% block content %}
  <h1>Books</h1>
  <div class="row">
    {% for category in page_obj %}
      <div class="col-md-12 mb-3">
        <div class="card">
          <div class="card-header">
            <h5>{{ category.name }}</h5>
          </div>
          <div class="card-body row">
            {% for book in category.random_books %}
              <div class="col-md-3 mb-3">
                <div class="card">
                  <div class="d-flex justify-content-center align-items-center" style="height: 300px;">
                    <img src="{% static book.img_path %}" class="card-img-top" alt="{{ book.title }}" style="max-height: 80%; max-width: 70%;">
                  </div>
                  <div class="card-body">
                    <h6 class="card-title">{{ book.title }}</h6>
                    <p class="card-text">{{ book.author }}</p>
                    <a href="{% url 'book_detail' book.id %}" class="btn btn-sm btn-primary">View Details</a>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
          <div class="card-footer">
            <a href="{% url 'category_books' category.id %}" class="btn btn-sm btn-warning btn-lg">Show more</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

  <!-- Pagination controls -->
  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1" aria-label="First">
            <span aria-hidden="true">&laquo;&laquo;</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% endif %}
      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <li class="page-item active">
            <span class="page-link">{{ num }}</span>
          </li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
            <span aria-hidden="true">&raquo;&raquo;</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endblock %}

templates/cart-detail.html
<!DOCTYPE html>
<html>

<head>
    <title>Order Summary</title>
</head>

<body>
    <h1>Order Summary</h1>
    <table>
        <thead>
            <tr>
                <th>Book Title</th>
                <th>Quantity</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart_items %}
            <tr>
                <td>{{ item.book.title }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.book.price }}</td>

            </tr>
            {% endfor %}
            <tr>
                <th>Total</th>
                <td></td>
                <td>{{ total_price }}</td>
            </tr>
        </tbody>
    </table>
</body>

</html>

templates/cart.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    View your Cart
{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="text-center my-4">Your Cart</h1>
        {% if cart_items %}
            <table class="table table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th>Book Title</th>
                        <th class="text-center align-middle">Quantity</th>
                        <th class="text-center align-middle">Price</th>
                        <th class="text-center align-middle">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart_items %}
                    <tr>
                        <td>{{ item.book.title }}</td>
                        <td class="text-center align-middle">{{ item.quantity }}</td>
                        <td class="text-center align-middle">{{ item.book.price }}</td>
                        <td class="text-center align-middle">
                            <a href="{% url 'remove_from_cart' item.book.title %}" class="btn btn-danger btn-sm">Remove</a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th class="text-center align-middle">Total</th>
                        <td></td>
                        <td class="text-center align-middle">{{ total_price }}</td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
            <div class="card">
                <div class="card-body text-center">
                    <a href="{% url 'check_out' %}" class="btn btn-primary btn-block">Proceed to Checkout</a>
                </div>
            </div>
        {% else %}
            <p class="text-center my-4">No Cart Available</p>
        {% endif %}
    </div>
{% endblock %}

templates/category_books.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  {{ category.name }} Books
{% endblock %}

{% block content %}
  <div class="row">
    <!-- Category Header -->
    <div class="col-md-12 mb-4">
      <h2 class="text-center">{{ category.name }}</h2>
      <hr class="my-4">
    </div>

    <!-- Category Books -->
    <div class="col-md-9 mx-auto">
      <div class="row">
        {% for book in page_obj %}
          <div class="col-md-3 mb-3">
            <div class="card">
              <img src="{% static book.img_path %}" class="card-img-top" alt="{{ book.title }}">
              <div class="card-body">
                <h5 class="card-title">{{ book.title }}</h5>
                <p class="card-text">{{ book.author }}</p>
                <a href="{% url 'book_detail' book.id %}" class="btn btn-sm btn-primary">View Details</a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>

  <!-- Pagination links -->
  <nav aria-label="Page navigation" class="mt-4">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1" aria-label="First">
            <span aria-hidden="true">&laquo;&laquo;</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% endif %}
      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <li class="page-item active">
            <span class="page-link">{{ num }}</span>
          </li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
            <span aria-hidden="true">&raquo;&raquo;</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endblock %}

templates/checkout.html
{% extends "base.html" %}

{% block title %}Checkout{% endblock %}  {% block content %}

<h1>Checkout</h1>

<form method="post">
    {% csrf_token %}
    <h2>Shipping Information</h2>

    <div class="form-group">
        <label for="id_shipping_address">Shipping Address:</label>
        <input type="text" name="shipping_address" id="id_shipping_address" required>
    </div>

    <div class="form-group">
        <label for="id_shipping_city">City:</label>
        <input type="text" name="shipping_city" id="id_shipping_city" required>
    </div>

    <div class="form-group">
        <label for="id_shipping_country">Country:</label>
        <input type="text" name="shipping_country" id="id_shipping_country" required>
    </div>

    <div class="form-group">
        <label for="id_postal_code">Postal Code:</label>
        <input type="text" name="postal_code" id="id_postal_code" required>
    </div>

    <div class="form-group">
        <label for="id_mobile">Mobile Number:</label>
        <input type="text" name="mobile" id="id_mobile">
    </div>

    <div class="form-group">
        <label for="id_payment_method">Payment Method:</label>
        <select name="payment_method" id="id_payment_method">
            {% for choice_value, choice_text in PAYMENT_CHOICES %}
                <option value="{{ choice_value }}">{{ choice_text }}</option>
            {% endfor %}
        </select>
    </div>

    <button type="submit">Place Order</button>
</form>

{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Home
{% endblock %}

{% block content %}
  <div class="row">
    <!-- Categories Sidebar -->
    <div class="col-md-3" style="margin-right: 20px;">
      <h2>Categories</h2>
      <div class="list-group">
        {% for category in categories %}
          <a href="{% url 'category_books' category.id %}" class="list-group-item list-group-item-action">{{ category.name }}</a>
        {% endfor %}
      </div>
    </div>
    
    <!-- Random Books -->
    <div class="col-md-8">
      <h2 class="text-center mb-4" style="color: #0066ff;">Favorite Books of The Day</h2>
      <div class="row justify-content-center">
        {% for book in random_books %}
          <div class="col-md-4 mb-3">
            <div class="card">
              <img src="{% static book.img_path %}" class="card-img-top" alt="{{ book.title }}">
              <div class="card-body">
                <h5 class="card-title">{{ book.title }}</h5>
                <p class="card-text">{{ book.author }}</p>
                <a href="{% url 'book_detail' book.id %}" class="btn btn-primary">View Details</a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}
    {% load socialaccount %}

    <div class="container mt-5">
        <h1 class="mb-4">Bookstore Web App</h1>
        {% if user.is_authenticated %}
            <div class="alert alert-success" role="alert">
                <p>Welcome, {{ user.username }}!</p>
            </div>
        {% else %}
            <div class="row">
                <div class="col-md-6 mb-4">
                    <h2>Sign In/Sign Up</h2>
                    <div class="d-grid gap-2">
                        <a href="{% provider_login_url 'github' %}" class="btn btn-dark btn-lg mb-2">Sign In/Sign Up with GitHub</a>
                    </div>
                </div>
                <div class="col-md-6">
                    <h2>Or, use your normal account</h2>
                    <form method="POST" action="{% url 'account_login' %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success btn-lg">Login</button>
                    </form>
                    <p class="mt-3">
                        Don't have an account? <a href="{% url 'account_signup' %}">Sign Up here</a>
                    </p>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Profile
{% endblock %}

{% block content %}
  <div class="container mt-5">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <h1 class="mb-4 text-center">Profile</h1>
        <div class="d-flex justify-content-end">
          <a href="{% url 'settings' %}" class="btn btn-link">
            <img src="{% static 'logo/setting.png' %}" alt="Settings" style="height: 20px;">
            Update Info
          </a>
        </div>
        <div class="card">
          <div class="card-header bg-primary text-white">
            <h5 class="mb-0">User Information</h5>
          </div>
          <div class="card-body">
            <div class="row mb-3">
              <div class="col-md-4 font-weight-bold">Username:</div>
              <div class="col-md-8">{{ user.username }}</div>
            </div>
            <div class="row mb-3">
              <div class="col-md-4 font-weight-bold">Email:</div>
              <div class="col-md-8">{{ user.email }}</div>
            </div>
            <div class="row mb-3">
              <div class="col-md-4 font-weight-bold">Full Name:</div>
              <div class="col-md-8">{{ user.get_full_name }}</div>
            </div>
          </div>
        </div>

        <h2 class="mt-5 mb-4 text-center">Addresses</h2>
        <div class="card">
          <div class="card-header bg-primary text-white">
            <h5 class="mb-0">User Addresses</h5>
          </div>
          <div class="card-body">
            {% for address in addresses %}
              <div class="mb-3">
                <p class="mb-1"><strong>Address Line:</strong> {{ address.address_line }}</p>
                <p class="mb-1"><strong>City:</strong> {{ address.city }}</p>
                <p class="mb-1"><strong>Postal Code:</strong> {{ address.postal_code }}</p>
                <p class="mb-1"><strong>Country:</strong> {{ address.country }}</p>
                <p class="mb-1"><strong>Mobile:</strong> {{ address.mobile }}</p>
                <hr>
              </div>
            {% empty %}
              <p>No addresses available.</p>
            {% endfor %}
          </div>
        </div>

        <h2 class="mt-5 mb-4 text-center">Payment Methods</h2>
        <div class="card">
          <div class="card-header bg-primary text-white">
            <h5 class="mb-0">Payment Methods</h5>
          </div>
          <div class="card-body">
            {% for payment in payments %}
              <div class="mb-3">
                <p class="mb-1"><strong>Payment Type:</strong> {{ payment.get_payment_type_display }}</p>
                <p class="mb-1"><strong>Expiry Date:</strong> {{ payment.expiry_date }}</p>
                <hr>
              </div>
            {% empty %}
              <p>No payment methods available.</p>
            {% endfor %}
          </div>
        </div>

        <!-- See your Wishlist Button -->
        <div class="text-center mt-4">
          <a href="{% url 'wishlist' %}" class="btn btn-primary">See your Wishlist</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/update_info.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Settings
{% endblock %}

{% block content %}
  <div class="container mt-5">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <h1 class="mb-4 text-center">Update Information</h1>
        <div class="card">
          <div class="card-header bg-primary text-white">
            <h5 class="mb-0">Update Your Information</h5>
          </div>
          <div class="card-body">
            <form method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-success">Save changes</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/user-information.html
<!DOCTYPE html>
<html>

<head>
    <title>Account Management</title>
</head>

<body>
    <h1>Account Management</h1>
    <form method="post" action="">
        {% csrf_token %}
        {{ edit.as_p }}
        <button type="submit">Save Changes</button>
    </form>
</body>

</html>